### ISSUE TITLE
Task:  diagrams  and documentation for debond protocol 

### ISSUE THREAD

**Issue by GrandGarcon** [Debond-Protocol/Docs#1]
# Description
Building the diagrams with miro explaining the workflow of contracts with application

- [x] complete the interfaces of each of the smart contracts with all of the overall interactions in the front-dapp in order to make the diagrams.

reference diagram: [Miro](https://miro.com/app/board/uXjVOQsK09c=/).

## Type of change

Please delete options that are not relevant.

- [ ] This change requires a documentation update

# Checklist:

- [ ] get feedback from Yu and team.

**Comment by dr-chain** [comment]
@GrandGarcon can you add the diagram for the liquidity made by @Edoumou
