### ISSUE TITLE
Wrong doc for Debond-Token

### ISSUE THREAD

**Issue by swiing** [Debond-Protocol/Docs#12]
**Describe the bug**
The doc for Debond-Token is a copy paste of the doc for Debond-ERC3475.

**Expected behavior**
It should be the doc for debond token instead.

**Comment by dhruvmalik007** [comment]
Thanks for checking out the issue. yes, these docs were mixed up during the commits. Currently we are adding an gitbook with up-to-date changes and will share the link once they are published next week.

**Comment by dhruvmalik007** [comment]
here it is : https://github.com/Debond-Protocol/Docs/blob/main/debond-protocol/Debond-Token/README.md . if you have any queries feel free to ask queries

**Comment by swiing** [comment]
Great! Thank you
